codes = {
  1: "Arrival Scan",
  2: "Departure Scan",
  11: "Received in Office",
  12: "Out for Delivery",
  -14: "Delivered",
  21: "Processed in Office",
  38: "Returned to Office",
  39: "Courier Pick-up",
  44: "Unsuccessful Delivery",
  69: "Deferred delivery",
  111: "Return to Sender",
  112: "Processed to the Insurance dept.",
  114: "Processed for Destruction",
  115: "Redirected",
  116: "Forwarded",
  121: "Stopped by Sender",
  123: "Refused by recipient",
  124: "Delivered Back to Sender",
  125: "Destroyed",
  127: "Theft/Burglary",
  128: "Canceled",
  129: "Administrative Closure",
  134: "Prepared for Self-collecting Consignee",
  144: "Handover for contents check/test",
  148: "Shipment data received",
  164: "Unsuccessful shipment pickup",
  169: "Delivery capacity reached (tour/office)",
  175: "Predict",
  176: "Export to foreign provider",
  181: "Unexpected delay",
  190: "Postponed delivery due to inaccurate/incomplete address",
  195: "Refuse contents check/test",
  217: "Handover to momentarily carrier",
  1134: "Notification sent for parcel in office/locker"
}


codes_bg_int = {
  1: "Сканиране при пристигане",
  2: "Сканиране при заминаване",
  11: "Приета в офис",
  12: "Предадена за разнос",
  -14: "Доставена",
  21: "Обработена в офис",
  38: "Върната в офис",
  39: "Приета от куриер",
  44: "Неуспешна доставка",
  69: "Отложена доставка",
  111: "Връщане към подател",
  112: "Предадена на отдел Застраховки",
  114: "Предадена за унищожаване",
  115: "Пренасочена",
  116: "Препратена",
  121: "Спряна от подател",
  123: "Отказ от получател",
  124: "Доставена обратно на подател",
  125: "Унищожена",
  127: "Кражба/Обир",
  128: "Анулирана",
  129: "Административно закриване",
  134: "Подготвена за получаване от клиент в офис",
  144: "Предадена за проверка/тест на съдържанието",
  148: "Получена информация за пратка",
  164: "Неуспешно вземане на пратка",
  169: "Достигнат капацитет за доставка (тур/офис)",
  175: "Predict",
  176: "Експорт към външен доставчик",
  181: "Неочаквано забавяне",
  190: "Отложена доставка поради неточен/непълен адрес",
  195: "Отказ от проверка/тест на съдържанието",
  217: "Предадена на междинен превозвач",
  1134: "Изпратено известие за пратка в офис/автомат"
}